from datetime import datetime
import pandas as pd
from reportlab.lib.pagesizes import A4
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors

def generate_pdf_report(results, user_query: str) -> str:
    """
    Generates a highly professional PDF report summarizing multi-agent findings,
    using ReportLab Platypus layout tools for clean grids, wrapping, and tables.
    """
    file_path = "agentic_pharma_report.pdf"
    
    # Page setup (A4 is 595.27 x 841.89 points)
    # Margins: 40 points
    doc = SimpleDocTemplate(
        file_path,
        pagesize=A4,
        rightMargin=40,
        leftMargin=40,
        topMargin=40,
        bottomMargin=40
    )
    
    styles = getSampleStyleSheet()
    
    # Create custom styles
    title_style = ParagraphStyle(
        'DocTitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=20,
        leading=24,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=6
    )
    
    subtitle_style = ParagraphStyle(
        'DocSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#64748b'),
        spaceAfter=15
    )
    
    h1_style = ParagraphStyle(
        'SectionH1',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=14,
        leading=18,
        textColor=colors.HexColor('#0f766e'), # Deep Teal
        spaceBefore=12,
        spaceAfter=8,
        keepWithNext=True
    )
    
    body_style = ParagraphStyle(
        'BodyTextCustom',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#334155'),
        spaceAfter=8
    )
    
    conclusion_style = ParagraphStyle(
        'ConclusionText',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=10,
        leading=15,
        textColor=colors.HexColor('#1e293b'),
        spaceAfter=0
    )
    
    table_header_style = ParagraphStyle(
        'TableHeader',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=9,
        leading=11,
        textColor=colors.white
    )
    
    table_cell_style = ParagraphStyle(
        'TableCell',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=11,
        textColor=colors.HexColor('#334155')
    )

    story = []
    
    # 1. Header Block
    story.append(Paragraph("Pharma Intelligence Report", title_style))
    story.append(Paragraph(
        f"Generated by Agentic Decision Support System  |  Date: {datetime.now().strftime('%B %d, %Y - %H:%M')}",
        subtitle_style
    ))
    
    # Query Summary Card
    query_content = [
        [Paragraph(f"<b>Target Research Query:</b> {user_query}", body_style)]
    ]
    query_table = Table(query_content, colWidths=[515])
    query_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('PADDING', (0, 0), (-1, -1), 8),
    ]))
    story.append(query_table)
    story.append(Spacer(1, 15))
    
    # 2. Executive Recommendation (Callout Box)
    story.append(Paragraph("Executive Recommendation", h1_style))
    conclusion_text = results.get("conclusion", "No combined conclusion was generated.")
    conclusion_content = [
        [Paragraph(conclusion_text, conclusion_style)]
    ]
    conclusion_table = Table(conclusion_content, colWidths=[515])
    conclusion_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f0fdfa')), # Light teal background
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#0d9488')), # Teal border
        ('LINELEFT', (0, 0), (0, -1), 4, colors.HexColor('#0d9488')), # Thick left border
        ('PADDING', (0, 0), (-1, -1), 12),
    ]))
    story.append(conclusion_table)
    story.append(Spacer(1, 15))
    
    # 3. Clinical Trials Section
    story.append(Paragraph("Clinical Evidence Assessment", h1_style))
    clinical_summary = results.get("clinical", {}).get("summary", "No clinical summary available.")
    story.append(Paragraph(clinical_summary, body_style))
    
    clinical_df = results.get("clinical", {}).get("trials", None)
    if isinstance(clinical_df, pd.DataFrame) and not clinical_df.empty:
        # Convert to list and wrap strings in Paragraph flowables
        data = [[Paragraph(f"<b>{col}</b>", table_header_style) for col in clinical_df.columns]]
        for _, row in clinical_df.iterrows():
            row_cells = []
            for col in clinical_df.columns:
                val = str(row[col])
                row_cells.append(Paragraph(val, table_cell_style))
            data.append(row_cells)
            
        clinical_table = Table(data, colWidths=[75, 110, 60, 75, 110, 85])
        clinical_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(clinical_table)
    story.append(Spacer(1, 15))
    
    # 4. Patent Section
    story.append(Paragraph("Intellectual Property & FTO Analysis", h1_style))
    patent_summary = results.get("patent", {}).get("summary", "No patent summary available.")
    story.append(Paragraph(patent_summary, body_style))
    
    patent_df = results.get("patent", {}).get("patents", None)
    if isinstance(patent_df, pd.DataFrame) and not patent_df.empty:
        data = [[Paragraph(f"<b>{col}</b>", table_header_style) for col in patent_df.columns]]
        for _, row in patent_df.iterrows():
            row_cells = []
            for col in patent_df.columns:
                val = str(row[col])
                row_cells.append(Paragraph(val, table_cell_style))
            data.append(row_cells)
            
        patent_table = Table(data, colWidths=[85, 110, 65, 65, 80, 110])
        patent_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#1e293b')),
            ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
            ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
            ('PADDING', (0, 0), (-1, -1), 5),
        ]))
        story.append(patent_table)
    story.append(Spacer(1, 15))
    
    # 5. Market Section
    story.append(Paragraph("Market Sizing & Commercial Potential", h1_style))
    market_summary = results.get("market", {}).get("summary", "No market summary available.")
    story.append(Paragraph(market_summary, body_style))
    
    market_data = results.get("market", {}).get("market_data", {})
    if market_data:
        m_size = market_data.get("estimated_size", "N/A")
        m_cagr = market_data.get("cagr", "N/A")
        m_comp = market_data.get("competition_level", "N/A")
        
        # Sizing summary grid
        sizing_content = [
            [
                Paragraph("<b>Estimated Market Size:</b>", table_cell_style), Paragraph(m_size, table_cell_style),
                Paragraph("<b>Projected CAGR:</b>", table_cell_style), Paragraph(m_cagr, table_cell_style)
            ],
            [
                Paragraph("<b>Competition Level:</b>", table_cell_style), Paragraph(m_comp, table_cell_style),
                Paragraph("<b>Analysis Region:</b>", table_cell_style), Paragraph(results.get("patent", {}).get("geography", "Global"), table_cell_style)
            ]
        ]
        sizing_table = Table(sizing_content, colWidths=[120, 137, 120, 138])
        sizing_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))
        story.append(sizing_table)
        
    doc.build(story)
    return file_path
